services:
  backend:
    image: alejoide/sheet-generator-backend:latest
    restart: unless-stopped
    env_file:
      - ./backend/.env
    networks:
      - default
  frontend:
    image: alejoide/sheet-generator-frontend:latest
    ports:
      - "4321:4321"
    restart: unless-stopped
    env_file:
      - ./frontend/.env
    networks:
      - default
      - nginx-proxy

networks:
  nginx-proxy:
    external: true