name: build-backend
on:
  push:
    tags:
      - "*"
jobs:
  build:
    name: Build and push
    runs-on: self-hosted
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          tags: |
            type=semver,pattern={{version}}
          images: alejoide/sheet-generator-backend
      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          tags: ${{ steps.meta.outputs.tags }}
          push: true
          file: ./backend/Dockerfile
