name: build-frontend
on:
  push:
    tags:
      - "*"
jobs:
  build:
    name: Build and push
    runs-on: self-hosted
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          tags: |
            type=semver,pattern={{version}}
          images: alejoide/sheet-generator-frontend
      - name: Add env files
        run: |
          APP_VERSION=${{ steps.meta.outputs.version }}
          echo "$FRONTEND_ENV_CONTENT" > ./frontend/.env
          echo "APP_VERSION=${APP_VERSION}" >> ./frontend/.env
        env:
          FRONTEND_ENV_CONTENT: ${{ secrets.FRONTEND_ENV_CONTENT }}
      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          tags: ${{ steps.meta.outputs.tags }}
          push: true
          file: ./frontend/Dockerfile
